/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wn518_printer_core_PrinterLib */

#ifndef _Included_com_wn518_printer_core_PrinterLib
#define _Included_com_wn518_printer_core_PrinterLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wn518_printer_core_PrinterLib
 * Method:    getBitmapData
 * Signature: ([III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wn518_printer_core_PrinterLib_getBitmapData
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_wn518_printer_core_PrinterLib
 * Method:    getBitmapDataWithHeader
 * Signature: ([III[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wn518_printer_core_PrinterLib_getBitmapDataWithHeader
  (JNIEnv *, jobject, jintArray, jint, jint, jbyteArray);

/*
 * Class:     com_wn518_printer_core_PrinterLib
 * Method:    getBitmapDataWithLineHeader
 * Signature: ([III[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wn518_printer_core_PrinterLib_getBitmapDataWithLineHeader
  (JNIEnv *, jobject, jintArray, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif//_Included_com_wn518_printer_core_PrinterLib
